version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
